ttsx/df_user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^register/$',views.index),
    url(r'^register_handle/$', views.register_handle),
    url(r'^register_exist/$', views.register_exist),
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    # url(r'^info/$',views.info),
    url(r'^user_center_info/$', views.user_center_info),
    url(r'^user_center_order/$', views.user_center_order),
    url(r'^user_center_site/$', views.user_center_site),
    url(r'^user_center_site_add/$', views.user_center_site_add),
    url(r'^logout/$', views.logout),
]

ttsx/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index),
    url(r'^detail/(?P<goods_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^list(\d+)_(\d+)/$',views.list),

]

ttsx/tiantian/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from goods import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),  
    url(r'^user/',include('df_user.urls')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^cart/',include('df_cart.urls')),
    url(r'^order/',include('df_order.urls')),
    #添加 副文本 编辑器
    url(r'^tinymce/', include('tinymce.urls')),
]

ttsx/df_order/models.py
from django.db import models

class OrderInfo(models.Model):
    oid = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6,decimal_places=2,null=True,blank=True)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    count = models.IntegerField()

ttsx/df_user/models.py
#coding=utf-8
from django.db import models

#用户
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    umail = models.CharField(max_length=64)
    ureceiver = models.CharField(max_length=20,default='')
    uadress =  models.CharField(max_length=100,default='')
    upostcode = models.CharField(max_length=6,default='')
    uphone = models.CharField(max_length=11,default='')

    def __str__(self):
        return self.uname

ttsx/df_user/views.py
#coding=utf-8
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,HttpRequest
from .models import *
from hashlib import sha1
from django.http import JsonResponse
import django
from goods.models import GoodsInfo
from df_user import user_decorator
from df_order.models import OrderDetailInfo,OrderInfo

#进入注册页面,输入ip后出发回车触发
def index(request):
    print(request.GET)
    # web应用的交互过程就是HTTP请求与响应的过程，打印request，我们会发现request就是一个实例化对象
    # 什么样的实例化对象呢？
    # 内容为：＂/user/register/＂,也就是把127.0.0.1:8000后面的内容制作成一个WSGIRequest对象(WSGIRequest继承http.HttpRequest)
    # 如何制作的呢？看django源代码
    # print(request,type(request))
    # <WSGIRequest: GET '/user/register/'> <class 'django.core.handlers.wsgi.WSGIRequest'>
    # print(isinstance(request,django.core.handlers.wsgi.WSGIRequest))
    # __bases__ 检测该类继承了哪个类，最后一定会追溯到object类
    # print(django.core.handlers.wsgi.WSGIRequest.__bases__)
    # print(HttpRequest.__bases__)
    # __mro__ 你所定义的任何一个类，python会计算出一个＂MRO 列表＂,该魔术方法就是查看这个列表
    # print(request,django.core.handlers.wsgi.WSGIRequest.__mro__)
    # print(isinstance(request,object))
    # 下面是render()方法,这个方法可神奇了,有六个参数， 其中有两个必须参数(request,template_name)
    return render(request,'df_user/register.html')

#判断账号是否被注册,失去焦点时触发
def register_exist(request):
    # ?uname='+$('#user_name').val()通过get的方式传参数
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    print(count)
    return JsonResponse({'count':count})

#如果账号没有被注册,则开始处理用户注册信息,提交后进入登录界面,点击注册后触发
def register_handle(request):
    uname = request.POST['user_name']
    upwd = request.POST['pwd']
    upwd2 = request.POST['cpwd']
    umail = request.POST['email']
    #判断两次输入的密码是否一致,不一致则进入注册页面
    if upwd != upwd2:
        return redirect('/user/register/')
    #对提交的密码加密,upwd3是加密后的密码
    s1 = sha1()
    s1.update(upwd.encode("gb2312"))
    upwd3 = s1.hexdigest()
    #创建UserInfo的实例化对象user,每一个用户的注册过程本质上讲都是一次实例化对象的过程
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.umail = umail
    user.save()
    # 这里采用重定向直接运行下面的函数
    return redirect('/user/login/')

#进入登录界面,重定向直接触发
def login(request):
    #request是WSGIRequest类的一个对象,COOKIES是WSGIRequest的一个方法,get是什么?
    #如果uname被存入cookie，则这里直接使用第一个参数uname,如果没有则为第二个参数
    #context参数'error_name','error_pwd'可以不填
    uname = request.COOKIES.get('uname','')
    context = {'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request,'df_user/login.html',context)

#填完数据进行处理,正常情况下，进入商场首页,点击登录后出触发
def login_handle(request):
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu',0)
    users = UserInfo.objects.filter(uname=uname)
    #判断数据库是否有当前用户名,没有则进入else直接输出“用户名错误”
    if len(users) == 1:
        s1 = sha1()
        s1.update(upwd.encode("gb2312"))
        #用户名正确的情况下，判断密码是否正确，不正确则进入else，输出“用户名错误”
        #正确且选择了“记住”,则用户名存入cookie,
        if s1.hexdigest() == users[0].upwd:
            url = request.session.get('url','/goods/')
            red = HttpResponseRedirect(url)
            if jizhu != 0:
                # 因为HttpResponseRedirect继承于HttpResponse，set_cookie()是HttpResponse的方法，
                # 所以set_cookie可以被HttpResponseRedirect的对象red调用
                red.set_cookie('uname',uname)
            else:
                red.set_cookie('uname','',max_age=-1)
            #将id与用户名存入数据库中的session表
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red

        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1}
            return render(request, 'df_user/login.html', context)

    else:
        context = {'title':'用户登录','error_name':1,'error_pwd':0}
        return render(request,'df_user/login.html',context)

def logout(request):
    request.session.flush()
    return redirect('/goods/')

#点击个人信息
@user_decorator.login
def user_center_info(request):
    user_mail = UserInfo.objects.get(id=request.session['user_id']).umail
    # 下面为获取浏览记录
    # 获取到的结果为一个字符串如:'2,4,5,6,7'或者''
    goods_ids = request.COOKIES.get('goods_ids','')
    # 将上面的字符串以','拆分为列表，结果为:['2','4','5','6','7']或者['']
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    # 没有浏览记录的时候goods_ids1为['']
    if goods_ids1 != ['']:
        for goods_id in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    context = {
        # 'title':'用户中心',
        'user_mail': user_mail,
        'user_name': request.session['user_name'],
        'goods_list': goods_list
    }
    return render(request,'df_user/user_center_info.html',context)

#点击全部订单
@user_decorator.login
def user_center_order(request):
    user_id = request.session['user_id']
    order = OrderInfo.objects.filter(user_id=user_id).order_by('-odate')
    return render(request,'df_user/user_center_order.html',{'order':order})

#点击送货地址
@user_decorator.login
def user_center_site(request):
    # 通过session获取一个对象（此对象为一个人的信息）,默认会显示用户为收件人
    user = UserInfo.objects.get(id=request.session['user_id'])
    return render(request,'df_user/user_center_site.html',{'user':user})

#添加收货人信息，可以改变默认收件人,填完收货地址，点击提交后触发
@user_decorator.login
def user_center_site_add(request):
    post = request.POST
    receiver = post.get('name')
    adress = post.get('adress')
    postcode = post.get('postcode')
    phone = post.get('phone')
    # 将填的收件人信息存入数据库,
    user = UserInfo.objects.get(id=request.session['user_id'])
    user.ureceiver = receiver
    user.uadress = adress
    user.upostcode = postcode
    user.uphone = phone
    user.save()
    return render(request,'df_user/user_center_site.html',{'user':user})

ttsx/templates/df_user/login.html
{% extends 'base_foot.html' %}
{% block head %}
<script type="text/javascript">
	$(function (){
	name_error=false;
	pwd_error=false;

	if({{ error_name }}==1){
		$('.user_error').html('用户名错误').show();
	}

	if({{ error_pwd }}==1){
		$('.pwd_error').html('密码错误').show();
	}
	})

</script>
{% endblock %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/goods/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ttsx/templates/df_user/register.html
{% extends 'base_foot.html' %}
{% block head %}<script type="text/javascript" src="/static/js/register.js"></script>{% endblock %}
{% block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a href="/goods/" class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock %}

ttsx/templates/df_user/user_center_info.html
{% extends 'base_userinfo.html' %}
{% block body_user %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="/user/user_center_info/" class="active">· 个人信息</a></li>
            <li><a href="/user/user_center_order/">· 全部订单</a></li>
            <li><a href="/user/user_center_site/">· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user_name }}</li>
                    <li><span>邮箱：</span>{{ user_mail }}</li>
                    <!--<li><span>联系方式：</span>{{ uphone }}</li>-->
                    <!--<li><span>联系地址：</span>{{ uadress }}</li>-->
                </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
            {% for goods in goods_list %}
                <li>
                    <a href="{%url 'goods:detail' goods.id %}"><img src="/static/{{ goods.gpic }}"></a>
                    <h4><a href="detail.html">{{ goods.gtitle }}</a></h4>
                    <div class="operate">
                        <span class="prize">{{ goods.gprice }}</span>
                        <span class="unit">{{ goods.gunit }}</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

ttsx/templates/df_user/user_center_order.html
{% extends 'base_userinfo.html' %}
{% block body_user %}
<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="/user/user_center_info/">· 个人信息</a></li>
			<li><a href="/user/user_center_order/" class="active">· 全部订单</a></li>
			<li><a href="/user/user_center_site/">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
			<h3 class="common_title2">全部订单</h3>
			{% for order in order %}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{ order.odate }}</li>
				<li class="col02">订单号：{{ order.oid }}</li>
				{% if order.oIsPay %}
					<li class="col02 stress">已支付</li>
				{% else %}
					<li class="col02 stress">未支付</li>
				{% endif %}
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							{% for order_detail in order.orderdetailinfo_set.all %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="/static/{{ order_detail.goods.gpic }}"></li>
								<li class="col02">{{ order_detail.goods.gtitle }}<em>{{ order_detail.goods.gprice }}元/{{ order_detail.goods.gunit }}</em></li>
								<li class="col03">{{ order_detail.count }}</li>
								<li class="col04"><span>{{ order_detail.goods.gprice }}</span>元</li>
							</ul>
							{% endfor %}
						</td>
						<td width="15%">{{ order.ototal }}元</td>
						{% if order.oIsPay %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						{% else %}
							<td width="15%">待付款</td>
							<td width="15%"><a href="/order/now_pay/{{ order.oid }}" class="oper_btn">去付款</a></td>
						{% endif %}
					</tr>
				</tbody>
			</table>
			{% endfor %}
			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
	</div>
</div>
{% endblock %}

ttsx/templates/df_user/user_center_site.html
{% extends 'base_userinfo.html' %}
{% block body_user %}
<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="/user/user_center_info/">· 个人信息</a></li>
			<li><a href="/user/user_center_order/">· 全部订单</a></li>
			<li><a href="/user/user_center_site/" class="active">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
			<h3 class="common_title2">收货地址</h3>
			<div class="site_con">
				<dl>
					<dt>收件人：</dt>
					<dd>{{ user.ureceiver }}</dd>
					<dt>当前地址：</dt>
					<dd>{{ user.uadress }} {{ user.uphone }}</dd>
				</dl>
			</div>
			<h3 class="common_title2">编辑地址</h3>
			<div class="site_con">
				<form action="/user/user_center_site_add/" method="post">
					<div class="form_group">
						<label>收件人：</label>
						<input type="text" name="name" value="">
					</div>
					<div class="form_group form_group2">
						<label>详细地址：</label>
						<textarea class="site_area" name="adress" value=""></textarea>
					</div>
					<div class="form_group">
						<label>邮编：</label>
						<input type="text" name="postcode" value="">
					</div>
					<div class="form_group">
						<label>手机：</label>
						<input type="text" name="phone" value="">
					</div>

					<input type="submit" name="" value="提交" class="info_submit">
				</form>
			</div>
	</div>
</div>
{% endblock %}